Repository OpenDevicePartnership/pcal6416a, pull requests merged in 2025-02, with the labels that each got.

#5 Fix license text
  LICENSE
Labels: documentation

#6 Update device-driver dependency
  Cargo.toml
Labels: bug

#7 Trim keywords to be able to publish crate
  Cargo.toml
Labels: documentation

#8 Update CODEOWNERS
  CODEOWNERS
Labels: enhancement
